export enum GitInfoActionType {
  "SET_GIT_INFO" = "GITINFO/SET_GIT_INFO",
  "LOAD_GIT_INFO_REQUEST" = "GITINFO/LOAD_GIT_INFO_REQUEST",
  "LOAD_GIT_INFO_SUCCESS" = "GITINFO/LOAD_GIT_INFO_SUCCESS",
  "LOAD_GIT_INFO_FAILURE" = "GITINFO/LOAD_GIT_INFO_FAILURE",
}
